backend:
  name: git-gateway
  branch: master

media_folder: "src/img" # Media files will be stored in the repo under src/img/uploads
public_folder: "img"  # The src attribute for uploaded media will begin with img/uploads

collections:
  - name: "default" # Used in routes, e.g., /admin/collections/blog
    label: "default label" # Used in the UI
    folder: "src/default" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "default string field", name: "title", widget: "string"}
      - {label: "default image field", name: "logo", widget: "image"}
      - {label: "default layout file", name: "layout", widget: "hidden", default: "default.pug"} # pug file in layouts dir
      - {label: "default hidden field", name: "hidden_field", widget: "hidden", default: "default"}
      - {label: "default content field", name: "body", widget: "markdown"}
